### ISSUE TITLE
Not able to use Birthday form type

### ISSUE THREAD

**Issue by soeren-helbig** [boekkooi/JqueryValidationBundle#39] opened 2016-03-29 11:45 UTC
I am trying to use the bundle (master) in connection with a `Birthday` form type. During the registration a user should input his birthday. The corresponding part of the form type looks like this:

```php
->add('birthday', 'birthday')
```

When the page is loaded, the JavaScript console outputs something like this (chrome):

```JavaScript
Uncaught TypeError: Cannot read property 'form' of undefined
```

The use of a standard `DateType` like the following works like a charme.

```php
->add('birthday', 'date', array(
    'years' => range(date('Y') -90, date('Y')),
))
```

**Comment by boekkooi** [comment] 2016-03-29 12:10
Hi @soeren-helbig I can't seem to reproduce this bug could you please provide a compile form example and tell me what version of Symfony and PHP you are using? Thanks!

**Comment by soeren-helbig** [comment] 2016-03-30 06:04
the form type looks something like this:

```php
class UserType extends AbstractType
{
    const FORM_NAME = 'appbundle_user';

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $range = function ($start, $end) {
            $ct = $start;
            $values = array();
            while ($end >= $ct) {
                $values[$ct] = $ct;
                $ct++;
            }
            return $values;
        };

        $builder
            ->add('gender', 'choice', array(
                    'label' => false,
                    'choices' => array(
                        User::GENDER_MALE => 'Herr',
                        User::GENDER_FEMALE => 'Frau'
                    ),
                    'multiple' => false,
                    'expanded' => false
                )
            )
            ->add('firstName', 'text', array(
                'label' => false,
                'attr' => array('placeholder' => 'Vorname*')
            ))
            ->add('lastName', 'text', array(
                'label' => false,
                'attr' => array('placeholder' => 'Nachname*')
            ))
            ->add('phone', 'text', array(
                'required' => false,
                'label' => false,
                'attr' => array('placeholder' => 'Telefon')
            ))
            ->add('email', 'text', array(
                'label' => false,
                'attr' => array('placeholder' => 'E-Mail*')
            ))
            ->add('birthday', 'birthday', array(
                'placeholder' => array(
                    'year' => 'Jahr',
                    'month' => 'Monat',
                    'day' => 'Tag'
                ),
                'label' => 'Geburtstag',
            ))
        ;
    }

    /**
     * @{inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\User',
        ));
    }

    /**
     * @{inheritdoc}
     */
    public function getName()
    {
        return self::FORM_NAME;
    }
}
```

i am running symfony 2.7.11 with php 5.6. hope this helps to reproduce the bug.

**Comment by boekkooi** [comment] 2016-03-30 08:57
@soeren-helbig Could you please provide me with the `AppBundle\Entity\User` class since the constraints look the be fetched from there.

**Comment by boekkooi** [comment] 2016-03-30 09:15
Please update composer and let me know if the error that I did find is the one you where having.

**Comment by soeren-helbig** [comment] 2016-04-01 06:31
looks good! ;) thx

**Comment by boekkooi** [comment] 2016-04-01 07:58
Great! I'm assuming I can close this issue now of not please reopen

**Closed by boekkooi** 2016-04-01 07:58 UTC
