### ISSUE TITLE
normalize group for null value

### ISSUE THREAD

**Issue by aitboudad** [boekkooi/JqueryValidationBundle#18] opened 2015-07-31 09:46 UTC
Form with submit btn doesn't work properly:
```
Warning: array_filter() expects parameter 1 to be array, null given in [FormRuleContext.php#L29](https://github.com/boekkooi/JqueryValidationBundle/blob/726f34e7c4cef101bf5b6b998346b342b45c42ed/src/Form/FormRuleContext.php#L29)
```

```php
$builder->add('submit', 'submit');
```
I think the default value for group should be array and not null [normalizeGroups](https://github.com/aitboudad/JqueryValidationBundle/commit/fe513354ea45864e8be94bbf19e220ba080e6814)

**Comment by boekkooi** [comment] 2015-08-02 12:51
Hi @aitboudad 

I'm unable to reproduce this error would it be possible to provide me with a example form + model? Also what symfony version are you using?

Thanks for reporting!

**Comment by aitboudad** [comment] 2015-08-02 13:52
@boekkooi here is an example to reproduce issue:

```php
    public function issues18Action(Request $request)
    {
        $form = $this->get('form.factory')->createNamedBuilder('')
            ->add('submit', 'submit')
            ->getForm();
        $this->handleForm($request, $form);

        return $this->render('::form.html.twig', array('form' => $form->createView()));
    }
```

**Comment by boekkooi** [comment] 2015-08-02 14:40
Thanks for the very quick response this should be fixed now

**Closed** 2015-08-02 14:39 UTC
